Readability update

diff --git a/wpshell b/wpshell
--- a/wpshell
+++ b/wpshell
@@ -18,7 +18,7 @@ COL_WHITE=$ESC_SEQ"38;5;231;02m"
 function wpshell(){
 clear
 echo -e "
-Type $COL_WHITE\"wpshell\"$COL_RESET to return to this menu:                         
+Type $COL_GREEN\"wpshell\"$COL_RESET to return to this menu:                         
   $COL_GREEN wpReplaceCore $COL_RESET  - Scan for WP Version and Backup/Replace Core Files
   $COL_GREEN coreLatest    $COL_RESET  - Backup/Replace WP Core Files With Latest Version
   $COL_GREEN dbexport      $COL_RESET  - Export WP Database
@@ -50,7 +50,7 @@ if [[ -z "$wpfiles" ]]; then
 	echo -e "No existing WordPress files found..."
 	else
 	oldWP="WPSHELL_CORE_$temp"
-	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
+	echo -e "Old WordPress files found! Moving them to$COL_CYAN$oldWP... $COL_RESET"
 	mkdir "$oldWP"
 	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
 fi
@@ -72,7 +72,7 @@ if [[ -f "$oldWP/wp-config.php" ]]; then
 	cp wp-config-sample.php wp-config.php
 	echo -e "$COL_RED\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
 fi
-echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
+echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_CYAN $oldWP.tar.gz $COL_RESET"
 wp --skip-plugins --skip-themes core update-db --quiet
 }
 ### WGET LATEST ###
@@ -100,7 +100,7 @@ if [[ -z "$wpfiles" ]]; then
 	echo -e "No existing WordPress files found..."
 	else
 	oldWP="WPSHELL_CORE_$temp"
-	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
+	echo -e "Old WordPress files found! Moving them to$COL_CYAN $oldWP... $COL_RESET"
 	mkdir "$oldWP"
 	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
 fi
@@ -122,7 +122,7 @@ if [[ -f "$oldWP/wp-config.php" ]]; then
 	cp wp-config-sample.php wp-config.php
 	echo -e "$COL_RED\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
 fi
-echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
+echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_CYAN $oldWP.tar.gz $COL_RESET"
 wp --skip-plugins --skip-themes core update-db --quiet
 }
 
@@ -130,11 +130,11 @@ wp --skip-plugins --skip-themes core update-db --quiet
 function dbexport(){
 # Get info from the wp globals
 getWPinfo
-
+temp=$(date -u +"%Y_%m_%d-%H_%M")
 echo "Starting export..."
 file="$2"
-[[ -z "$file" ]] && file="WPSHELL_$dbname"_$(now).sql
-mysqldump -h "$dbhost" -u "$dbuser" -p"$dbpass" "$dbname" > "$file" && echo -e "Exported database '$dbname' to file '$file'\n" || echo -e "Failed to export database '$dbname' to file '$file'!\n"
+[[ -z "$file" ]] && file="WPSHELL_$dbname"_$temp.sql
+mysqldump -h "$dbhost" -u "$dbuser" -p"$dbpass" "$dbname" > "$file" && echo -e "$COL_GREEN\rExported database '$dbname' to file '$file'\n $COL_RESET" || echo -e "$COL_RED\rFailed to export database '$dbname' to file '$file'!\n $COL_RESET"
 }
 
 ########## BACKEND FUNCTIONS ##########
